{{- if and .Values.running .Values.mysql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phraseanet-db
spec:
  replicas: 1
  strategy:
      type: Recreate
  selector:
    matchLabels:
      app: phraseanet
      tier: db
  template:
    metadata:
      labels:
        app: phraseanet
        tier: db
    spec:
    {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
    {{- end }}
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: {{ .Values.mysql.pvc_name }}
      {{ if .Values.image.pullSecret.enabled }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret.name }}
      {{ end }}
      containers:
      - name: db
        image: {{ .Values.image.registry }}/phraseanet-db:{{ .Values.image.tag.phraseanet }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        terminationMessagePolicy: FallbackToLogsOnError
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ tpl .Values.mysql.root_password $ }}
        - name: MYSQL_USER
          value: {{ tpl .Values.mysql.user $ }}
        - name: MYSQL_PASSWORD
          value: {{ tpl .Values.mysql.password $ }}
        - name: MYSQL_MAX_ALLOWED_PACKET
          value: {{ .Values.mysql.max_allowed_packet }}
        - name: MYSQL_MAX_CONNECTION
          value: {{ .Values.mysql.max_connection | quote }}
        - name: MYSQL_CONNECT_TIMEOUT
          value: {{ .Values.mysql.connect_timeout | quote }}
        - name: MYSQL_WAIT_TIMEOUT
          value: {{ .Values.mysql.wait_timeout | quote }}
        - name: MYSQL_LONG_QUERY_TIME
          value: {{ .Values.mysql.long_query_time | quote }}
        - name: MYSQL_SLOW_QUERY_LOG
          value: {{ .Values.mysql.slow_query_log | quote }}
        - name: MYSQL_KEY_BUFFER_SIZE
          value: {{ .Values.mysql.key_buffer_size | quote }}
        - name: MYSQL_QUERY_CACHE_SIZE
          value: {{ .Values.mysql.query_cache_size | quote }}
        - name: MYSQL_QUERY_CACHE_LIMIT
          value: {{ .Values.mysql.query_cache_limit | quote }}
        volumeMounts:
        - name: "database"
          mountPath: "/var/lib/mysql"
{{- end }}
